spring:
  application:
    name: farmaorder

  datasource:
    url: jdbc:postgresql://localhost:5432/farmaorder_db
    username: farmaorder_user
    password: farmaorder_pass

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE